name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  pre-tests:
    uses: ./.github/workflows/pre-tests.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
